<?php include __DIR__ . '/../header.html'; ?>
    <div class="container">
        <div class="row">
            <h3>Adicionar categorias</h3>
            <h5><?= "Produto - {$product->getName()}" ;?></h5>
            <form name="form" method="post" action="<?= "/products/{$product->getId()}/set-categories";?>">
                <div class="form-group">
                    <label for="Categories">Categorias</label>
                    <select class="form-control" name="categories[]" multiple>
                        <?php foreach ($categories as $category): ?>
                            <option
                                value="<?= $category->getId();?>" <?= $product->getCategories()->contains($category)? "selected": "";?>>
                                <?= $category->getName();?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button type="submit"  class="btn btn-default">Enviar</button>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html'; ?>


