<?php include __DIR__ . '/../header.html'; ?>
    <div class="container">
        <div class="row">
            <h3>Novo produto</h3>
            <form name="form" method="post" enctype="multipart/form-data" action="/products/store">

                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Digite o nome">
                </div>

                <div class="form-group">
                    <label for="amount">Quantidade</label>
                    <input type="number" class="form-control" id="amount" name="amount" placeholder="Digite a quantidade">
                </div>

                <div class="form-group">
                    <label for="price">Preço</label>
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                        <input type="number" class="form-control" id="price" name="price" placeholder="Digite o preço">
                        <div class="input-group-addon">.00</div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="image">Preço</label>
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                        <input type="file" class="form-control" id="image" name="image" placeholder="Selecione uma imagem">
                        <div class="input-group-addon">.00</div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" rows="10" id="description" name="description" placeholder="Digite a descrição"></textarea>
                </div>

                <div class="form-group">
                    <label class="radio-inline">
                        <input type="radio" id="spotlight2" name="spotlight" value="0" checked="checked">
                        Comum
                    </label>
                    <label class="radio-inline">
                        <input type="radio" id="spotlight1" name="spotlight" value="1">
                        Destaque
                    </label>
                    <label class="radio-inline">
                        <input type="radio" id="spotlight3" name="spotlight" value="2">
                        Promoção
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
    </div>

<?php include __DIR__ . '/../footer.html'; ?>