<?php include __DIR__ . '/../header.html'; ?>
    <div class="container">
        <div class="row">
            <h3>Listagem de Produtos</h3>
            <a href="/products/create">Novo Produto</a>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Id:</th>
                        <th scope="col">Nome:</th>
                        <th scope="col">Quantidade:</th>
                        <th scope="col">Preço:</th>
                        <th scope="col">Destaque:</th>
                        <th scope="col">Ações:</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($products as $product): ?>
                        <tr>
                            <td><?= $product->getId(); ?></td>
                            <td><?= $product->getName(); ?></td>
                            <td><?= $product->getAmount(); ?></td>
                            <td><?= $product->getPrice(); ?></td>
                            <td><?= $product->getSpotlight()==0?"Comum":"Destaque"; ?></td>
                            <td>
                                <?= "<a href='/products/{$product->getId()}/categories'>Categorias</a>"; ?> |
                                <?= "<a href='/products/{$product->getId()}/edit'>Editar</a>"; ?> |
                                <?= "<a href='/products/{$product->getId()}/remove'>Excluir</a>"; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

<?php include __DIR__ . '/../footer.html'; ?>