<?php include __DIR__ . '/../header.html'; ?>
    <div class="container">
        <div class="row">
            <h3>Listagem de categorias</h3>
            <a href="/categories/create">Nova Categoria</a>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Id:</th>
                        <th scope="col">Nome:</th>
                        <th scope="col">Ações:</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($categories as $category): ?>
                        <tr>
                            <td><?= $category->getId(); ?></td>
                            <td><?= $category->getName(); ?></td>
                            <td><?= "<a href='/categories/{$category->getId()}/edit'>Editar</a>"; ?> |
                                <?= "<a href='/categories/{$category->getId()}/remove'>Excluir</a>"; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

<?php include __DIR__ . '/../footer.html'; ?>