<?php include __DIR__ . '/header.html'; ?>
<br/>
<br/>

    <div class="container">
        <div class="row">
            <h3>Produtos & Categorias</h3>
            <div class="col-md-9">
                <ul class="list-unstyled">
                    <li>
                        <?php foreach ($products as $product) : ?>

                                <div class="col-sm-12 col-md-6 col-lg-4">
                                    <div class="thumbnail">
                                        <img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzE0MHgxNDAKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNjZlMWFmNjdlMSB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE2NmUxYWY2N2UxIj48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA2MjUiIHk9Ijc0LjU1NjI1Ij4xNDB4MTQwPC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="...">
                                        <div class="caption">
                                            <h4 style="color: #23a1d1"><?= $product->getName(); ?></h4>
                                            <p><?= substr($product->getDescription(), 0, 90); ?></p>
                                            <button type="button" class="btn btn-sm btn-primary" data-toggle="popover" title="Descrição" data-content="<?= $product->getDescription(); ?>">Ver mais</button>
                                        </div>
                                    </div>
                                </div>
                        <?php endforeach; ?>
                    </li>
                </ul>
            </div>



            <div class="list-group col-md-3">
                <a href="/" class="list-group-item active">
                    Todas
                </a>
                <?php foreach ($categories as $category) : ?>
                    <li class="list-group-item">
                        <a href="<?= "/?search={$category->getId()}"; ?>"><?= $category->getName(); ?></a>
                    </li>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

<?php include __DIR__ . '/footer.html'; ?>